baseURL = "https://cpmores.github.io/" # 改为 HTTPS
title = "Cpmores"
languageCode = "en-us"
theme = "hello-friend-ng"

[outputs]
home = ["HTML", "RSS", "JSON"] # 启用搜索

[taxonomies]
tag = "tags" # 启用标签

[params]
dateform = "Jan 2, 2006"
dateformShort = "Jan 2"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"
homeSubtitle = "A place to hide, I am an Ostrich" # 首页副标题
enableSharingButtons = true                 # 按钮
enableGlobalLanguageMenu = true              # 多语言切换
disableReadOtherPosts = false                # 显示其他文章链接

[params.search]
enable = true    # 启用搜索
backend = "fuse" # 使用 Fuse.js

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/posts/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 30

[markup.goldmark.renderer]
unsafe = true # 允许原始 HTML（如 iframe）
